### ISSUE TITLE
Support for TURN server

### ISSUE THREAD

**Issue by shyim** [fmeringdal/nettu-meet#7]
To improve the connectivity I would like to use a turn server like coturn. This seems currently not useable

**Comment by fmeringdal** [comment]
TURN servers are only relevant if you have a P2P architecture, so that the mediastream can fallback on a central server to relay the mediasoup over to the other peer in case the P2P connection cannot be established.
Nettu Meet uses mediasoup (which is not P2P) internally to handle mediastreams and connectivity and STUN and TURN is therefore not relevant.

Did you experience any issues with the connectivity of this project?

**Comment by shyim** [comment]
Ahh sorry
